services:
  stats-server:
    build: ./stats/stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=12345
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/actuator" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
          - POSTGRES_DB=statsdb
          - POSTGRES_USER=statsuser
          - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d \"$$POSTGRES_DB\" -U \"$$POSTGRES_USER\""]
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    container_name: ewm-service
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator" ]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
            - POSTGRES_DB=ewmdb
            - POSTGRES_USER=ewmuser
            - POSTGRES_PASSWORD=12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d \"$$POSTGRES_DB\" -U \"$$POSTGRES_USER\""]
      timeout: 5s
      interval: 5s
      retries: 10
